A0-340: wait in CI until consensus begins
Cardinal-Cryptography/aleph-node pull request #110
Opened 2021-09-01 12:38 UTC by fbielejec

2021-09-16 09:41 UTC, bartoszjedrzejewski requested changes

2021-09-16 09:41 UTC, bartoszjedrzejewski commented on docker/docker_entrypoint.sh
> +PUBLIC_ADDR=${PUBLIC_ADDR:-/ip4/127.0.0.1/tcp/$PORT}
Replace that, by adding 

> if [[ -n "${PUBLIC_ADDR:-}" ]]; then
>   ARGS+=(--public-addr "${PUBLIC_ADDR}")
> fi

at the end, after FLAG_L_ALEPH_BFT.

2021-09-16 09:41 UTC, bartoszjedrzejewski commented on docker/docker_entrypoint.sh
> +  --public-addr "${PUBLIC_ADDR}"
We don't want to hardcode this. See comment above.

2021-09-16 09:41 UTC, bartoszjedrzejewski commented on docker/docker_entrypoint.sh
> +echo "My public address to advertize is: $PUBLIC_ADDR"
There's really no need for this in final form.

2021-09-16 09:43 UTC, bartoszjedrzejewski approved these changes

2021-09-17 00:07 UTC, skrolikowski-10c approved these changes

2021-09-17 03:53 UTC, merged