AZ-676: pure aggregator
Cardinal-Cryptography/aleph-node pull request #343
Opened 2022-03-18 08:57 UTC by piotrMocz

Splits the `BlockSignatureAggregator` into two parts:
* the _pure_ part, only containing the core logic (still called `BlockSignatureAggregator`)
* the _impure_/networking part, containing the channels and very simple sending logic (called `IO` but imported as `AggregatorIO`).

The `IO` methods take the aggregator as an argument: making the aggregator into one of `IO`'s fields makes the code more succint, although at the cost of slightly breaking the semantics of `IO` -- I'm open to discussion ;)

2022-03-18 09:02 UTC, deuszx commented on finality-aleph/src/aggregation/aggregator.rs
> +    metrics: Option<Metrics<H>>,
Isn't inclusion of metrics here making this _technically_ impure again?

2022-03-18 09:05 UTC, deuszx commented
Did you consider making the _pure_ part of the aggregator a member of its IO counterpart? You would still get the advantage of being able to easily unit-test it. 

On the other hand, is there a change that we may have multiple different `Aggregator`s but single `AggregatorIO`?

2022-03-18 09:21 UTC, piotrMocz commented
Yes, I actually started out that way: it makes the code easier to read but
strictly speaking the aggregator is not IO, so this is a trade off between
readability and good semantics 🙂

W dniu pt., 18.03.2022 o 10:06 deuszx ***@***.***> napisał(a):

> Did you consider making the *pure* part of the aggregator a member of its
> IO counterpart? You would still get the advantage of being able to easily
> unit-test it.
>
> On the other hand, is there a change that we may have multiple different
> Aggregators but single AggregatorIO?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Cardinal-Cryptography/aleph-node/pull/343#issuecomment-1072213785>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAXXGDLDGMOMIV732NGMRNLVARBP5ANCNFSM5RBG4DEA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-18 09:26 UTC, deuszx commented
> Yes, I actually started out that way: it makes the code easier to read but strictly speaking the aggregator is not IO, so this is a trade off between readability and good semantics 🙂 

But the `AggregatorIO` kind of is, right? I think it's not only about good semantics though. The way it's encoded right now would allow for multiple, different aggregators to be passed to the same `AggregatorIO` but would it be correct? There is a set of channels there that are fed with some data. Each element can be consumed only once. What if someone makes a mistake and uses the same `AggregatorIO` on multiple `Aggregator`s? That would probably get both into an invalid state since elements from the channels are supposed to be passed on to the same, single `Aggregator`.

2022-03-18 09:48 UTC, piotrMocz commented
> > Yes, I actually started out that way: it makes the code easier to read but strictly speaking the aggregator is not IO, so this is a trade off between readability and good semantics slightly_smiling_face
> 
> But the `AggregatorIO` kind of is, right? I think it's not only about good semantics though. The way it's encoded right now would allow for multiple, different aggregators to be passed to the same `AggregatorIO` but would it be correct? There (in the `AggregatorIO`) is a set of channels there that are fed with some data. Each element can be consumed only once. What if someone makes a mistake and uses the same `AggregatorIO` on multiple `Aggregator`s? That would probably get both into an invalid state since elements from the channels are supposed to be passed on to the same, single `Aggregator`.

That's a very valid point and I agree -- I'll be happy to make the change provided that @timorl agrees as well ;)

2022-03-18 18:17 UTC, deuszx commented
@piotrMocz , looks like @timorl gave a silent approval :P

2022-03-21 10:43 UTC, piotrMocz commented
> @piotrMocz , looks like @timorl gave a silent approval - that's how I'm interpreting the thumbs-up see_no_evil

@deuszx yes, he even confirmed that in a meeting, so we're good to go -- I made the change :slightly_smiling_face:

2022-03-21 13:44 UTC, timorl requested changes
Nice, some minor comments.

2022-03-21 13:44 UTC, timorl commented on finality-aleph/src/aggregation/aggregator.rs
> +    fn on_multisigned_hash(&mut self, multisigned_hash: MS) -> AggregatorResult {
This shouldn't be returning a result if it cannot ever return an error – I thought this was a mistake in a logging message about network failing below, but the problem actually is here.

2022-03-21 13:44 UTC, timorl commented on finality-aleph/src/aggregation/aggregator.rs
> +    AggregatorError(AggregatorError),
I don't think you need this, you actually handle all aggregator errors internally to `IO`, see a comment below for the single usage and why it should be removed.

2022-03-21 13:44 UTC, timorl commented on finality-aleph/src/aggregation/aggregator.rs
> +                Err(_) => {}
This looks mysterious, perhaps spell out the other kind of error you expect here (`NoHashFound`) and ignore it, while logging any unexpected error as problematic (although you can likely ignore it in the logic, it'll never happen anyway).

2022-03-21 16:49 UTC, timorl approved these changes

2022-03-22 08:41 UTC, merged