Light Client benchmarks
Cardinal-Cryptography/aleph-node pull request #363
Opened 2022-03-31 10:04 UTC by fbielejec

This PR adds the benchmarking to the LC pallet. The baseline numbers (`weights.rs`) are generated are on my machine, we should probably follow up with a task that runs them on the same hardware our validators are running on.

2022-04-22 13:04 UTC, deuszx commented
Can we extract the unrelated changes to separate PRs? For example:
* addition of the benchmark command could be merged directly to `main`, correct?
* adding an RPC server for the pallet could be a separate PR
* etc.

So that this one contains only the benchmark code.

2022-04-26 23:10 UTC, deuszx commented on pallets/tendermint-light-client/src/lib.rs
> +        type WeightInfo: WeightInfo;
`mock.rs` does not compile for me b/c it's missing this type now.

2022-04-29 09:40 UTC, fbielejec commented
> Can we extract the unrelated changes to separate PRs? For example:
> 
> * addition of the benchmark command could be merged directly to `main`, correct?
> * adding an RPC server for the pallet could be a separate PR
> * etc.
> 
> So that this one contains only the benchmark code.

AFAIK all the changes in this PR are related to the benchmarks only.

2022-05-04 12:08 UTC, Marcin-Radecki requested changes
Most of the comments are questions and docs requests.

2022-05-04 12:08 UTC, Marcin-Radecki commented on pallets/tendermint-light-client/src/benchmarks.rs
> +        verify {
I can see that `update_client` has a lot of corner cases, I assume we test here only sunny case scenario which is the most complex from runtime pov?

2022-06-08 08:38 UTC, fbielejec commented on pallets/tendermint-light-client/README.md
> +./target/release/aleph-node benchmark --chain docker/data/chainspec.json --extrinsic='*' --pallet=pallet-tendermint-light-client s --template=./.maintain/pallet-weight-template.hbs --output ./pallets
Done

2022-06-08 08:46 UTC, fbielejec commented
@Marcin-Radecki  I fixed the most obvious points you raised, but I'm merging as-is to the upstream branch - no point in spending more time on it since it goes to the freezer for the foreseeable future :shrug:

2022-06-08 13:29 UTC, merged