A0-825 Unit buffer overflow
Cardinal-Cryptography/aleph-node pull request #410
Opened 2022-05-06 14:55 UTC by lesniak43

2022-05-06 15:41 UTC, timorl requested changes

2022-05-06 15:41 UTC, DamianStraszak approved these changes

2022-05-06 15:44 UTC, lesniak43 commented on finality-aleph/src/network/service.rs
> +                match sender.unbounded_send(data) {
fixed

2022-05-09 08:06 UTC, timorl approved these changes

2022-05-09 08:07 UTC, merged