A0-952 calculate totals once
Cardinal-Cryptography/aleph-node pull request #439
Opened 2022-05-23 12:02 UTC by kostekIV

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Infrastructure updated accordingly
- [ ] I have made corresponding changes to the documentation
- [ ] New documentation created
- [ ] Bump `spec_version` and `transaction_version` if relevant
- [ ] Bump `aleph-client` version if relevant

2022-05-24 13:05 UTC, mike1729 requested changes
One q and one req for naming convention change.

2022-05-24 13:05 UTC, mike1729 commented on pallets/elections/src/impls.rs
> +    fn populate_totals_on_next_era_start(start_index: SessionIndex) {
Why `next` in name. It should and works for current era, right? `_on_new_era_start`?

2022-05-24 17:17 UTC, maciejnems approved these changes
LGTM. Just some nits

2022-05-25 07:04 UTC, kostekIV commented on pallets/elections/src/lib.rs
> +pub type Total = u32;
Now it is `TotalReward`

2022-05-25 07:04 UTC, kostekIV commented on pallets/elections/src/lib.rs
> +pub type Total = u32;
Now it is `TotalReward`

2022-05-25 07:05 UTC, kostekIV commented on pallets/elections/src/impls.rs
> +    fn compute_validator_scaled_totals(era: EraIndex) {
good catch, renamed

2022-05-25 07:05 UTC, kostekIV commented on pallets/elections/src/impls.rs
>      fn populate_reserved_on_next_era_start(start_index: SessionIndex) {
in both function I changed the argument name to just `session`, are you ok with that?

2022-05-25 07:05 UTC, kostekIV commented on pallets/elections/src/impls.rs
>      fn populate_reserved_on_next_era_start(start_index: SessionIndex) {
in both function I changed the argument name to just `session`, are you ok with that?

2022-05-25 08:40 UTC, maciejnems commented on pallets/elections/src/impls.rs
>      fn populate_reserved_on_next_era_start(start_index: SessionIndex) {
I think that `next_index` for `populate_reserved_on_next_era_start` and `start_index` for `populate_totals_on_new_era_start` would be more aligned with how `SessionManager` looks, but just just session is fine with me.

2022-05-25 08:40 UTC, maciejnems approved these changes

2022-05-25 08:46 UTC, merged