A0-1115 : Basic test for correct reward points calculation
Cardinal-Cryptography/aleph-node pull request #522
Opened 2022-07-11 14:20 UTC by krzysztofziobro

2022-07-13 09:58 UTC, maciejzelaszczyk requested changes
Great work :) Two minor points, other than that LGTM

2022-07-13 09:58 UTC, maciejzelaszczyk commented on e2e-tests/src/test/rewards.rs
> +    let end_era_session = sessions_per_era * wait_for_next_era(&root_connection)?;
Shouldn't this be `start_new_era_session`? Or something like that.

2022-07-13 09:58 UTC, maciejzelaszczyk commented on e2e-tests/src/test/rewards.rs
> +        let members_bench = non_reserved_members
There's a function for that: `get_bench_members`.

2022-07-14 10:31 UTC, piotrMocz reviewed
I have nothing to add besides what @maciejzelaszczyk commented, in general the PR looks good so I'll accept once you address those comments ;)

2022-07-14 13:35 UTC, maciejzelaszczyk approved these changes
Very nice :)

2022-07-14 14:48 UTC, piotrMocz approved these changes
Cool!

2022-07-15 08:06 UTC, merged